### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ilv** [TheTorProject/gettorbrowser-old#1]
@DonnchaC and @aagbsn have proposed to update the README of this repo in order to get it indexed and thus provide better results for people trying to download Tor Browser. It will also be helpful to have this README localized and maybe have a landing page too. I'm opening this ticket to discuss the idea. cc @azadi @mrphs

p.s. I think this should be done irrespective if we use releases or not.

**Comment by ilv** [comment]
Below is a proposal:

# Download Tor Browser

In this repository you will find links to download the latest version of
Tor Browser, which currently is x.yz. Please select one of the links below:

## Windows
[Download Tor Browser](https://link.to.file) (English) ([signature file](https://link.to.file)).
[Download Tor Browser](https://link.to.file) (Farsi) ([signature file](https://link.to.file)).
[Download Tor Browser](https://link.to.file) (Turksih) ([signature file](https://link.to.file)).
[Download Tor Browser](https://link.to.file) (Chinese) ([signature file](https://link.to.file)).

## OS X
[Download Tor Browser](https://link.to.file) (English) ([signature file](https://link.to.file)).
[Download Tor Browser](https://link.to.file) (Farsi) ([signature file](https://link.to.file)).
[Download Tor Browser](https://link.to.file) (Turksih) ([signature file](https://link.to.file)).
[Download Tor Browser](https://link.to.file) (Chinese) ([signature file](https://link.to.file)).

## Linux 32-bit
[Download Tor Browser](https://link.to.file) (English) ([signature file](https://link.to.file)).
[Download Tor Browser](https://link.to.file) (Farsi) ([signature file](https://link.to.file)).
[Download Tor Browser](https://link.to.file) (Turksih) ([signature file](https://link.to.file)).
[Download Tor Browser](https://link.to.file) (Chinese) ([signature file](https://link.to.file)).

## Linux 64-bit
[Download Tor Browser](https://link.to.file) (English) ([signature file](https://link.to.file)).
[Download Tor Browser](https://link.to.file) (Farsi) ([signature file](https://link.to.file)).
[Download Tor Browser](https://link.to.file) (Turksih) ([signature file](https://link.to.file)).
[Download Tor Browser](https://link.to.file) (Chinese) ([signature file](https://link.to.file)).

**Comment by ilv** [comment]
We have two options here:

1. We update this file and push it to the repo each time a new version is released.
2. We make this file static (with no mention to a specific version) and have a 'latest' folder (or release) with the bundles of the latest version. This means we should rename bundle files and replace the version number by 'latest' or something.

Once we have this done we should try to translate it to several languages (at the very least the ones listed for download)

**Comment by ilv** [comment]
Also, we could create a github page for this repo with the same content and use the [old repo](https://github.com/gettorbrowser) I was using for this purpose and create gettorbrowser.github.io with the same content.

**Comment by azadi** [comment]
(2) is what we do for TorBirdy, however, we were discussing this yesterday for Tor Messenger and it was suggested that one of the reasons the "latest" approach (2) is bad because it doesn't tell the user which version they downloaded.  What do you think?

**Comment by azadi** [comment]
`gettorbrowser.github.io` sounds good, but `thetorproject.github.io` would make users feel more comfortable perhaps?

**Comment by DonnchaC** [comment]
A GitHub site at `gettorbrowser.github.io` would be nice for some users but not very censorship resistant. It would be much easier for a censor to perform a DNS block on that domain than the main `github.com` domain.

**Comment by DonnchaC** [comment]
For generating the README.md, how about creating a template which can be used to generate the README file during each update? We could a Jinja template in this repository which gettor can use to fill out the Markdown file?

**Comment by ilv** [comment]
@azadi Yes, I think that is why there is no 'latest' in [https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions](RecommendedTBBVersions) too. We should specify what version of Tor Browser the user is going to download. Creating a template sounds good @DonnchaC 

@DonnchaC you are right about github.com vs *.github.io, but I think the more mirrors we have, the better. That said, I vote for creating the README in this repo, along with landing pages in gettorbrowser.github.io and thetorproject.github.io (if possible). I prefer someone finds links to the *.github.io pages rather than links to sketchy pages out there.

**Comment by DonnchaC** [comment]
I think the Github releases and README should also include Orbot on Orfox APKs. Many users just have mobile devices and it should be easy for them to get Tor too.

Lantern (https://getlantern.org) and Psiphon (https://psiphon3.com/en/download.html) are doing a better job on their product presentation. For example both of these link to the Android application first, and Psiphon even includes QR codes. It should be pretty straightforward to commit QR codes which link to the APK's hosted on Github to the repo.

**Comment by ilv** [comment]
I totally agree. Let's start with distributing the APK files, we can include QR codes later.

**Comment by ilv** [comment]
Alright, I've created a [script](https://gitweb.torproject.org/gettor.git/tree/create_gh_mirrors.py) to automatically update the README file and the [landing page](https://thetorproject.github.io/gettor). I also renamed this repo and created a new one called gettorbrowser, which from now on will only have the releases. I will delete this repo in a day or two.

p.s. as you may notice, we are already using releases for v5.5.2 :)
